[versions]

minecraft = "1.21.11"
loader = "0.18.2"
loom = "1.14-SNAPSHOT"
fabric = "0.139.4+1.21.11"

lombok = "1.18.42"
gson = "2.13.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }